更新oicq版本到2.1.8
Clansty/Q2TG pull request #7
Opened 2021-12-10 03:48 UTC by twfb

2021-12-10 14:21 UTC, Clansty requested changes
如果可以的话把回复的检测做了吧，貌似是放到另一个字段里了QAQ

不想做的话就等我有空了我来写

2021-12-10 14:21 UTC, Clansty commented on handlers/handleTgMsgDelete.ts
> +        //if ((await qq.deleteMsg(qMsgId)).error) {
所以为啥这里注释掉了呀

2021-12-10 14:21 UTC, Clansty commented on utils/processQQMessage.ts
> +                message.replyTgId = await getTgByQQ(m.id)
回复需要单独处理呢，因为 2.0 已经弃用这个了

2021-12-16 02:49 UTC, twfb commented
用的时候发现登录不上就改了改 也不是专业前端 供大佬参考吧

2021-12-16 03:13 UTC, Clansty commented
嗯嗯，等我空了我来改一下

2022-03-27 13:39 UTC, Clansty commented
我基于 OICQ 2.x 重构的版本马上就要转到主线了，所以这个 PR 就先 Close 了

2022-03-27 13:39 UTC, closed without merging